In [1]:
def compute():
    try:
        val=5/0
    except:
        print("exception ocurrred")

compute()

exception ocurrred


In [3]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for i in range(2):
    for j in range(2):
        for k in range(2):
            print(subjects[i]+" " + verbs[j]+" " + objects[k])

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [23]:
import numpy as np
Num=[2,3,4,5]
N= len(Num)
arr=np.zeros((N,N),dtype=int)
for i in range(N):
    for j in range(N):
        arr[j][i]=Num[j]**(N-1-i)
        
print(arr)        
        

[[  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
